export enum ActionType {

    GET_VIDEOGAMES = 'GET GAMES',
    GET_BY_NAME = 'GET BY NAME',
    GET_BY_ID = 'GET BY ID',
    GET_GENRES = 'GET GENRES',
    CREATE_GAME = 'CREATE GAME',
    FILTER_BY_ORIGIN = 'FILTER BY ORIGIN',
    FILTER_BY_GENRE = 'FILTER BY GENRE',
    ORDER_BY_ABC = 'ORDER BY ABC',
    ORDER_BY_RATING = 'ORDER BY RATING',
    LOADING = 'LOADING',
    RESET_VIDEOGAMES = 'RESET_VIDEOGAMES',
    RESET_GAME_DETAILS = 'RESET GAME DETAILS',

}

